#! /bin/sh
 
# Installation
# - Move this to /etc/init.d/conflict-detector
# - chmod +x this
#
# Starting and stopping
# - Start: `service conflict-detector start` or `/etc/init.d/conflict-detector start`
# - Stop: `service conflict-detector stop` or `/etc/init.d/conflict-detector stop`
 
#ref http://till.klampaeckel.de/blog/archives/94-start-stop-daemon,-Gearman-and-a-little-PHP.html
#ref http://unix.stackexchange.com/questions/85033/use-start-stop-daemon-for-a-php-server/85570#85570
#ref http://serverfault.com/questions/229759/launching-a-php-daemon-from-an-lsb-init-script-w-start-stop-daemon
 
NAME=conflict-detector
DESC="Git Conflict Detector"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"
 
DAEMON="/bin/bash"
DAEMON_OPTS="exec /var/www/detect_conflicts_daemon.php >> ${LOGFILE} 2>&1"
DAEMON_WORKING_DIR="/var/www"
 
 
test -x $DAEMON || exit 0
 
set -e
 
case "$1" in
    start)
        echo -n "Starting ${DESC}: "
        start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} --chdir ${DAEMON_WORKING_DIR} --startas ${DAEMON} -- -c "${DAEMON_OPTS}" >> ${LOGFILE}
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --pidfile ${PIDFILE}
        echo "$NAME."
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --pidfile ${PIDFILE}
        sleep 1
        start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} --chdir ${DAEMON_WORKING_DIR} --startas ${DAEMON} -- -c "${DAEMON_OPTS}" >> ${LOGFILE}
        echo "$NAME."
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac
 
exit 0